services:
  
  # Servizio 1: API Core (Logica di Prenotazione)
  paguro_api:
    build: 
      context: .
      dockerfile: Dockerfile_API 
    container_name: paguro_api_service
    ports:
      - "5000:80" 
    environment:
      - API_TOKEN=${PAGURO_API_TOKEN}
      - DB_HOST=paguro_db
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - DB_NAME=${DB_NAME}
      - OLLAMA_HOST=ollama:11434 
    depends_on:
      - paguro_db
      - ollama
    restart: always

  # Servizio 2: Database (PostgreSQL raccomandato)
  paguro_db:
    image: postgres:14-alpine
    container_name: paguro_db_service
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - db_data:/var/lib/postgresql/data 
    restart: always

  # Servizio 3: LLM (Ollama)
  ollama:
    image: ollama/ollama
    container_name: paguro_ollama_service
    volumes:
      - ollama_data:/root/.ollama
    # FIX: Avvia il server e pulla il modello phi3 automaticamente
    command: >
      /bin/sh -c "
        (ollama serve &)
        sleep 5
        ollama pull phi3:3.8b # MODELLO LEGGERO
        wait
      "
    restart: always

# Volumi per la persistenza dei dati
volumes:
  db_data:
  ollama_data:
